FROM microsoft/dotnet

LABEL maintainer="dheenadhayalan@gmail.com"


WORKDIR /api

COPY . .

RUN dotnet build
RUN dotnet publish -o /publish

WORKDIR /publish

ENTRYPOINT [ "dotnet", "/publish/api.dll" ]
